"""cascade lesson progress deletion

Revision ID: 62fdaffec25e
Revises: f5cd8d795cd4
Create Date: 2026-10-08 09:07:48.048604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fdaffec25e'
down_revision: Union[str, Sequence[str], None] = 'f5cd8d795cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lesson_progress_lesson_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.create_foreign_key('lesson_progress_lesson_id_fkey', 'lesson_progress', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lesson_progress_lesson_id_fkey', 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_progress_lesson_id_fkey'), 'lesson_progress', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
