"""Add course status

Revision ID: ee7790097fdf
Revises: 701c0268fc99
Create Date: 2026-08-17 13:47:41.073101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7790097fdf'
down_revision: Union[str, Sequence[str], None] = '701c0268fc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
