"""add user regional preferences

Revision ID: f7ca8e81f24e
Revises: 62fdaffec25e
Create Date: 2026-10-09 13:14:05.508792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ca8e81f24e'
down_revision: Union[str, Sequence[str], None] = '62fdaffec25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.String(length=20), server_default='kazakhstan', nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'region')
    # ### end Alembic commands ###
