services:
  postgres:
    image: postgres:17

    container_name: edumind_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: edumind_db
      POSTGRES_USER: edumind_user
      POSTGRES_PASSWORD: edumind_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: